### ISSUE TITLE
Replacing Screens

### ISSUE THREAD

**Issue by hughrawlinson** [emfcamp/badge-2024-documentation#112]
We should document that it's possible to replace the screen, and how to do it

**Comment by andypiper** [comment]
This is [mentioned in the end user manual already](https://github.com/emfcamp/badge-2024-documentation/blob/b4bcbf84f867570b4d0821bb5cf63352f6192188/docs/using-the-badge/end-user-manual.md?plain=1#L78), although there's no explicit instructions on how to pull it out, solder on headers, and push back in. It might be better to move it to the common problems page?

**Comment by npentrel** [comment]
done!
