### ISSUE TITLE
WiFi Settings Error

### ISSUE THREAD

**Issue by edent** [emfcamp/badge-2024-documentation#170]
I've got a mpremote shell on the Tildagon and am following the instructions for setting up WiFi at https://tildagon.badge.emfcamp.org/using-the-badge/connect-to-wifi/#option-2-use-tildagon-flasher

I get this error:

```
>>> import settings
>>> settings.set("wifi_ssid", "MyNetwork")
>>> settings.set("wifi_password", "Password123")
>>> settings.set("wifi_wpa2ent_username", None)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "settings.py", line 29, in set
KeyError: wifi_wpa2ent_username
```
(I've tried both single quotes and double.)

I can connect using this following code - but it doesn't save the settings:

```
>>> import network
>>> w = network.WLAN(network.STA_IF)
>>> w.connect("MyNetwork", "Password123")
>>> w.status()
1010
>>> w.isconnected()
True
```

Any clues as to what I'm doing wrong?

**Comment by npentrel** [comment]
I got that error too, you should still be able to then call `settings.save()` and it should then save the wifi settings and you should be able to restart the badge then. 
Unsure why that is happening though

**Comment by edent** [comment]
Thanks - that seemed to work. Should I make a PR to remove that from the documentation?

**Comment by npentrel** [comment]
I'll merge your PR because it's useful to have. I am under the impression the `wifi_wpa2ent_username` is needed for people on such networks so I need to follow up with the team on that...
