### ISSUE TITLE
Test code on EEPROM

### ISSUE THREAD

**Issue by npentrel** [emfcamp/badge-2024-documentation#176]
We haven't been able to test the code in [App loaded from EEPROM](https://tildagon.badge.emfcamp.org/hexpansions/writing-hexpansion-apps/#app-loaded-from-eeprom) because of https://github.com/emfcamp/badge-2024-software/issues/81. If anyone doesn't have that issue and can test the code, please do.

**Comment by walkerdanny** [comment]
Have finally had chance to test this - it looks like the example app does get launched, but it needs to request to be foregrounded to have its `draw` or `update` methods called. Will make a pull request with a fix.
