### ISSUE TITLE
Document the Text Widget

### ISSUE THREAD

**Issue by hughrawlinson** [emfcamp/badge-2024-documentation#186]
https://github.com/emfcamp/badge-2024-software/issues/16

We have a [text widget and layout system](https://github.com/emfcamp/badge-2024-software/blob/main/modules/app_components/layout.py) that needs documenting.

[More info](https://github.com/emfcamp/badge-2024-software/issues/34)

**Comment by npentrel** [comment]
Fixed in https://github.com/emfcamp/badge-2024-documentation/pull/194
