### ISSUE TITLE
Images not loading in documentation site

### ISSUE THREAD

**Issue by gklyne** [emfcamp/badge-2024-documentation#205]
**Describe the bug**

Browsing to https://tildagon.badge.emfcamp.org/using-the-badge/end-user-manual/, not all images are loading.  If I try to follow the image links (e.g. https://tildagon.badge.emfcamp.org/using-the-badge/images/badge-photos/screws1.jpg), I get 404 response.

The images display OK in Github:
https://github.com/emfcamp/badge-2024-documentation/blob/main/docs/using-the-badge/end-user-manual.md

**To Reproduce**

Browse to https://tildagon.badge.emfcamp.org/using-the-badge/end-user-manual/

Some images are not displayed (e.g. "Screw mounts" in Assembly, section 1.

**Expected behavior**

Expect to see images.  Expect to click through and see images.

**Screenshots**

![image](https://github.com/emfcamp/badge-2024-documentation/assets/557566/fe41e909-ba5c-4cb4-8e20-9c6817c8b612)

**Additional context**

Using Brave browser on MacxOS.  Similar problem with Firefox.  Some images display OK, but others do not (see screenshot).

**Comment by npentrel** [comment]
Thank you! I think this is fixed now!

**Comment by gklyne** [comment]
Yes, works now, thanks.
