### ISSUE TITLE
Consider changing colour scheme

### ISSUE THREAD

**Issue by npentrel** [emfcamp/badge-2024-documentation#219]
The purple is I think the default, could change that to our colours https://www.emfcamp.org/about/branding

**Comment by andypiper** [comment]
The main thought I have on this is that the branding colours are (AFAIK) specific to the theming for a particular year. It might be nice to use them if it makes sense and looks readable, but OTOH, maybe the badge needs its own branding choices, a default that stands alone from the year of the event, or has a stylesheet that can be applied on a biannual basis in line with the current iteration.

**Comment by npentrel** [comment]
Changed this for now
