### ISSUE TITLE
Preview image does not use correct colour theme

### ISSUE THREAD

**Issue by npentrel** [emfcamp/badge-2024-documentation#222]
done some investigation with mkdocs but unsure how to change

**Comment by andypiper** [comment]
Pretty sure this is via the `mkdocs-material` plugin and the `social` section of the `mkdocs.yml` file. I have never tried tweaking this myself.

**Comment by npentrel** [comment]
Yes that's correct but I've not been able to get it to work. There's something with material insiders that would do it but I think it's paid and would make contributions harder. By default it seems to use the primary colour but I've tried setting it to green and it won't change the preview image

**Comment by walkerdanny** [comment]
The change I've implemented in #223 seems to fix this? At least it fixes the cache that gets generated when serving the docs, assume that's the same. I set it to the mid green rather than the dark green so the logo shows up.

**Comment by npentrel** [comment]
I've checked out the branch and when I go to `http://127.0.0.1:8000/assets/images/social/index.png` it still displays as purple. I'm happy to merge through, maybe it's something about my local machine...

**Comment by npentrel** [comment]
Yeah still all purple on https://www.opengraph.xyz/url/https%3A%2F%2Ftildagon.badge.emfcamp.org%2F

**Comment by walkerdanny** [comment]
That same URL displays as green for me, strange! Maybe the cache needs to update?

![image](https://github.com/emfcamp/badge-2024-documentation/assets/16877618/6d66639c-c717-49dc-b668-0edb524423fc)

**Comment by npentrel** [comment]
That's so odd. if you inspect the html source on the deployed site, can you search for `og:image` and tell me what URL it goes to?
for me that's
https://tildagon.badge.emfcamp.org/assets/images/social/index.png

**Comment by walkerdanny** [comment]
Yep, same URL for me, and fetching it shows up as purple. Is there a way to force the deployed site to clear its cache of files and rebuild the images? I'd have thought it would do that automatically when being redeployed but maybe not?

**Comment by npentrel** [comment]
Hosted on GitHub Pages, I don't think we can do anything. I guess we'll wait a bit and see if it changes.

**Comment by walkerdanny** [comment]
To get it to work locally I deleted the .cache folder and that forced mkdocs to rebuild everything, so it feels like this must be the same issue.

**Comment by npentrel** [comment]
I can see it now! I spend like 2h yesterday changing settings and wondering why nothign was changing

**Comment by npentrel** [comment]
There was a cache being created in the github action. I managed to delete it and it's now working. Thank you so much for fixing it and finding the cache folder!
