### ISSUE TITLE
A somewhat minimal example app that calls an API

### ISSUE THREAD

**Issue by npentrel** [emfcamp/badge-2024-documentation#69]
This can go into the [`tildagon-apps/api.md`](https://tildagon.badge.emfcamp.org/tildagon-apps/api/) folder on the website. Don't worry about the format too much, it doesn't have to be perfect, even if there's no text and just code, that would be helpful.

An idea we had was to use the [pokemon api](https://pokeapi.co/) and just display a random pokemon but anything that does a simple api call and displays info would be great!

**Comment by ntflix** [comment]
Built a simple example to fetch and display current weather at EMFCamp location. [Check out the repo here](https://github.com/ntflix/Tildagon-Weather).

**Comment by npentrel** [comment]
This is now closed as we've added two examples to the docs. If anyone else has been working on an example please feel free to still add it though!
