### ISSUE TITLE
Improve documentation for flashing apps

### ISSUE THREAD

**Issue by MikeS159** [emfcamp/badge-2024-documentation#96]
I have not been able to find documentation related to flashing apps over USB. I have something working in the simulator, but not on device. Currently the only was I can get an app on there is via the store. A 15 min delay when trying to debug isn't ideal.

**Comment by MikeS159** [comment]
I was just shown how to do this. Will update the docs with instructions.

**Comment by npentrel** [comment]
@MikeS159 have you seen https://tildagon.badge.emfcamp.org/tildagon-apps/development/#debug-your-app-on-your-badge ?

**Comment by MikeS159** [comment]
My bad, I though it was just for debugging, missed the bit on copying. Any objections to my added a child page on using Thonny? A program with a UI might be easier for some people.

**Comment by npentrel** [comment]
No problem - it's good feedback and means I now made it more findable. And absolutely go for it
